### ISSUE TITLE
Retrigger doesnt quite work

### ISSUE THREAD

**Issue by Drewol** [guusw/unnamed-sdvx-clone#7] opened 2016-06-17 09:23 UTC
First, in BeatmapFromKSH, `else if(c >= 'S' && c <= 'W') // Retrigger 8/16/32/12/24` set the effect type to Gate instead of Retrigger.

Second, in DSP.cpp on RetriggerDSP::Process, `if(m_loops < 0)` wont work because the loop count starts at 0 so that wouldnt add any samples so it should be `if(m_loops < 1)`

After I fixed both of those the effect would only work if I had hit the note from the very start, if i picked up the note halfway through the audio completely disappeared. 

Edit: After changing so that the effect track uses the nofx file and also removing the part where the combo decides whether to use effects or not the issue seems to be resolved

**Comment by guusw** [comment] 2016-06-20 14:39
The retrigger should be fixed now, I couldn't reproduce the issue where it would not work when holding it halfway during the note though.

**Closed** 2016-06-26 16:42 UTC
